{{- if .Values.controller.horizontalPodAutoscaler }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kgateway.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kgateway.fullname" . }}
  {{- with .Values.controller.horizontalPodAutoscaler }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
