{{- if .Values.controller.verticalPodAutoscaler }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "kgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kgateway.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kgateway.fullname" . }}
  {{- with .Values.controller.verticalPodAutoscaler }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
