apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: example-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "example.com"
  rules:
    - backendRefs:
        - name: example-svc
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /foo
    - backendRefs:
        - name: example-svc
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /bar
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: test
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: gateway-test
spec:
  targetRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: example-gateway
  jwtAuth:
    extensionRef:
      name: jwt-ext-1
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: jwt-ext-1
spec:
  type: JWT
  jwt:
    providers:
    - name: my-example1
      claimsToHeaders:
      - name: org
        header: x-org
      - name: email
        header: x-email
      issuer: https://dev1.example.com
      jwks:
        local:
          configMapRef:
            name: jwt-ext-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-ext-1
data:
  jwks: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAruK9KacQjDePRyfG7oPI
    aqAIyCeOCBIGB2nBbDLGp1Szdm7rsWcrzGf7Avpa/ijLV9huoNvpdflld4B+SaT7
    m3EDDMDUyA4LayJC5JBI10Qfu3Qn8BEpcdN2uRiycXOzgsoIXneXp9hENlS5Vsr3
    ur5BaBCc+BZZRRaXDTLy6KyD1Pyd6XRsxyZXt/SYOIww0NSt5u0CTyZUGJhQungJ
    pI8Hhrzdf87mLZGZd16dOGObE5LqFwk2prN3D0+owLsA25WJOPZXizxpTB4tPvJu
    YGATajDpzrHf+WXgOgvwyxaHJSN/fE+eFuRT3ooDaAuytsfYotsn4z/ajdEPSwXY
    CwIDAQAB
    -----END PUBLIC KEY-----